In [1]:
!pip install pandas numpy matplotlib seaborn statsmodels pandas-gbq catboost scikit-learn
import pandas as pd
import os
import pandas_gbq as pd_gbq
import seaborn as sns
import numpy as np
import statsmodels
import matplotlib.pyplot as plt
import statsmodels.api as sm
import sklearn
import  catboost as cb
from sklearn.model_selection import train_test_split
# local modules
os.chdir('/home/jovyan/Domrachev files/Digital incremental newbies model')
from digital_model import train_country_newbies_model
from elast_simulation import simulate_budget_elasticity

Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 14.3 MB/s
Collecting numpy
  Downloading numpy-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.5 MB)
     |████████████████████████████████| 19.5 MB 89.0 MB/s
Collecting matplotlib
  Downloading matplotlib-3.9.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
     |████████████████████████████████| 8.3 MB 96.3 MB/s
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     |████████████████████████████████| 294 kB 85.2 MB/s
Collecting statsmodels
  Downloading statsmodels-0.14.5-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (10.7 MB)
     |████████████████████████████████| 10.7 MB 97.6 MB/s
Collecting pandas-gbq
  Downloading pandas_gbq-0.29.2-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 13 kB/s
Collecting catboost
  Downloading catboost-1.2.8-cp39-cp39-manylinux2014_x86_64.whl (99.2 MB)
     |████████████████████████████████| 99.2 MB 142 kB/s
Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
     |████████████████████████████████| 13.5 MB 95.9 MB/s
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.9/site-packages (from pandas) (2.8.2)
Collecting tzdata>=2022.7
  Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
     |████████████████████████████████| 347 kB 108.2 MB/s
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.7-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 93.0 MB/s
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.9/site-packages (from matplotlib) (21.2)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.9/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in /opt/conda/lib/python3.9/site-packages (from matplotlib) (5.4.0)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (321 kB)
     |████████████████████████████████| 321 kB 109.3 MB/s
Collecting pillow>=8
  Downloading pillow-11.3.0-cp39-cp39-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
     |████████████████████████████████| 6.6 MB 93.0 MB/s
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.60.1-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.8 MB)
     |████████████████████████████████| 4.8 MB 96.2 MB/s
Collecting scipy!=1.9.2,>=1.8
  Downloading scipy-1.13.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
     |████████████████████████████████| 38.6 MB 86.9 MB/s
Collecting patsy>=0.5.6
  Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
     |████████████████████████████████| 232 kB 108.1 MB/s
Collecting packaging>=20.0
  Downloading packaging-25.0-py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 7.9 MB/s
Collecting google-api-core<3.0.0,>=2.10.2
  Downloading google_api_core-2.26.0-py3-none-any.whl (162 kB)
     |████████████████████████████████| 162 kB 110.9 MB/s
Collecting google-auth-oauthlib>=0.7.0
  Downloading google_auth_oauthlib-1.2.2-py3-none-any.whl (19 kB)
Collecting google-auth>=2.13.0
  Downloading google_auth-2.41.1-py2.py3-none-any.whl (221 kB)
     |████████████████████████████████| 221 kB 104.6 MB/s
Collecting pyarrow>=4.0.0
  Downloading pyarrow-21.0.0-cp39-cp39-manylinux_2_28_x86_64.whl (42.7 MB)
     |████████████████████████████████| 42.7 MB 31.1 MB/s
Collecting google-cloud-bigquery<4.0.0,>=3.4.2
  Downloading google_cloud_bigquery-3.38.0-py3-none-any.whl (259 kB)
     |████████████████████████████████| 259 kB 103.3 MB/s
Collecting db-dtypes<2.0.0,>=1.0.4
  Downloading db_dtypes-1.4.3-py3-none-any.whl (18 kB)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.9/site-packages (from pandas-gbq) (58.3.0)
Collecting pydata-google-auth>=1.5.0
  Downloading pydata_google_auth-1.9.1-py2.py3-none-any.whl (15 kB)
Collecting plotly
  Downloading plotly-6.3.1-py3-none-any.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 116.6 MB/s
Requirement already satisfied: six in /opt/conda/lib/python3.9/site-packages (from catboost) (1.16.0)
Collecting graphviz
  Downloading graphviz-0.21-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 7.6 MB/s
Collecting joblib>=1.2.0
  Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
     |████████████████████████████████| 308 kB 115.2 MB/s
Collecting threadpoolctl>=3.1.0
  Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Collecting googleapis-common-protos<2.0.0,>=1.56.2
  Downloading googleapis_common_protos-1.70.0-py3-none-any.whl (294 kB)
     |████████████████████████████████| 294 kB 115.6 MB/s
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5
  Downloading protobuf-6.32.1-cp39-abi3-manylinux2014_x86_64.whl (322 kB)
     |████████████████████████████████| 322 kB 114.5 MB/s
Collecting proto-plus<2.0.0,>=1.22.3
  Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 10.5 MB/s
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /opt/conda/lib/python3.9/site-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.26.0)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
     |████████████████████████████████| 181 kB 111.4 MB/s
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Collecting cachetools<7.0,>=2.0.0
  Downloading cachetools-6.2.0-py3-none-any.whl (11 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Collecting google-resumable-media<3.0.0,>=2.0.0
  Downloading google_resumable_media-2.7.2-py2.py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 17.4 MB/s
Collecting google-cloud-core<3.0.0,>=2.4.1
  Downloading google_cloud_core-2.4.3-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: zipp>=3.1.0 in /opt/conda/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.6.0)
Collecting narwhals>=1.15.1
  Downloading narwhals-2.7.0-py3-none-any.whl (412 kB)
     |████████████████████████████████| 412 kB 118.3 MB/s
Collecting grpcio-status<2.0.0,>=1.33.2
  Downloading grpcio_status-1.75.1-py3-none-any.whl (14 kB)
Collecting grpcio<2.0.0,>=1.33.2
  Downloading grpcio-1.75.1-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 97.9 MB/s
Collecting google-crc32c<2.0dev,>=1.0
  Downloading google_crc32c-1.7.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37 kB)
Collecting pyasn1<0.7.0,>=0.6.1
  Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 2.5 MB/s
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.9/site-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.0.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.9/site-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2021.10.8)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.1.1)

Collecting typing-extensions~=4.12
  Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 4.8 MB/s
Installing collected packages: pyasn1, typing-extensions, rsa, pyasn1-modules, protobuf, cachetools, proto-plus, grpcio, googleapis-common-protos, google-auth, tzdata, requests-oauthlib, numpy, grpcio-status, google-crc32c, google-api-core, pyarrow, pillow, pandas, packaging, narwhals, kiwisolver, google-resumable-media, google-cloud-core, google-auth-oauthlib, fonttools, cycler, contourpy, threadpoolctl, scipy, pydata-google-auth, plotly, patsy, matplotlib, joblib, graphviz, google-cloud-bigquery, db-dtypes, statsmodels, seaborn, scikit-learn, pandas-gbq, catboost
  Attempting uninstall: packaging
    Found existing installation: packaging 21.2
    Uninstalling packaging-21.2:
      Successfully uninstalled packaging-21.2
Successfully installed cachetools-6.2.0 catboost-1.2.8 contourpy-1.3.0 cycler-0.12.1 db-dtypes-1.4.3 fonttools-4.60.1 google-api-core-2.26.0 google-auth-2.41.1 google-auth-oauthlib-1.2.2 google-cloud-bigquery-3.38.0 google-cloud-core-2.4.3 google-crc32c-1.7.1 google-resumable-media-2.7.2 googleapis-common-protos-1.70.0 graphviz-0.21 grpcio-1.75.1 grpcio-status-1.75.1 joblib-1.5.2 kiwisolver-1.4.7 matplotlib-3.9.4 narwhals-2.7.0 numpy-2.0.2 packaging-25.0 pandas-2.3.3 pandas-gbq-0.29.2 patsy-1.0.1 pillow-11.3.0 plotly-6.3.1 proto-plus-1.26.1 protobuf-6.32.1 pyarrow-21.0.0 pyasn1-0.6.1 pyasn1-modules-0.4.2 pydata-google-auth-1.9.1 requests-oauthlib-2.0.0 rsa-4.9.1 scikit-learn-1.6.1 scipy-1.13.1 seaborn-0.13.2 statsmodels-0.14.5 threadpoolctl-3.6.0 typing-extensions-4.15.0 tzdata-2025.2

In [2]:
# get_data
import pandas_gbq as pd_gbq

with open("digital_data_set_querry.SQL", "r", encoding="utf-8") as f:
    sql = f.read()

df = pd_gbq.read_gbq(sql)
# df['newbies_total'] = df['vertical_newbies_delivery_paid']+df['vertical_newbies_delivery_organic']

Downloading: 100%|██████████|

In [3]:
result = train_country_newbies_model(
    df,
    seed=42,
    holdout_days=30,
    half_life_days=60,
    top_n_countries=15,
    target_column = 'vertical_newbies_delivery_paid',
    catboost_params={"iterations": 3000, "learning_rate": 0.05}
)

In [4]:
result['metrics_overall']

,rmse,mae,wmape_pct,rows,unique_days,unique_countries,holdout_start,last_date,train_last_date
0,44.337465,24.446948,5.642645,450,30,15,2025-09-02,2025-10-01,2025-09-01

In [5]:
result['feature_importance']

                              feature  importance
0                             cpi_raw   16.156641
1                        country_name   12.683159
2                             eff_raw   10.310621
3                          cost_total    8.972722
4         cost_modelled_courier_lag14    7.348977
5          cost_modelled_rh_passenger    4.750837
6     cost_modelled_rh_passenger_lag1    3.697731
7         cost_modelled_courier_roll7    3.669778
8   cost_modelled_rh_passenger_roll14    3.378181
9          cost_modelled_courier_lag1    2.892243
10   cost_modelled_rh_passenger_roll7    2.584337
11                      log_cpi_roll7    2.565577
12                          eff_roll7    2.534698
13                          cpi_roll7    2.259320
14                   cost_total_roll7    2.091340
15                  cost_total_roll14    1.863744
16    cost_modelled_rh_passenger_lag7    1.742543
17                    cost_total_lag1    1.606615
18         cost_modelled_courier_lag7    1.519081
19                           cpi_lag1    1.456689
20                           eff_lag1    1.394233
21   cost_modelled_rh_passenger_lag14    1.225674
22                      log_eff_roll7    0.781571
23       cost_modelled_rh_driver_lag7    0.352594
24              cost_modelled_courier    0.319074
25            cost_modelled_rh_driver    0.295738
26                                dow    0.280173
27                   cost_total_lag14    0.234906
28                    cost_total_lag7    0.220378
29                     is_after_horiz    0.186057
30                         is_weekend    0.168175
31      cost_modelled_rh_driver_roll7    0.116143
32                          month_num    0.115324
33       cost_modelled_rh_driver_lag1    0.104623
34      cost_modelled_rh_driver_lag14    0.067551
35     cost_modelled_rh_driver_roll14    0.037885
36       cost_modelled_courier_roll14    0.015068

In [6]:
elast_paid = simulate_budget_elasticity(
    model=result["model"],
    df_model=result["df_model"],
    feature_columns=result["feature_columns"],
    categorical_features=result["categorical_features"],
    target_col="vertical_newbies_delivery_paid",
    start_date=result["holdout_start"],
    end_date=result["last_date"],
    budg_down=0.90,
    budg_up=1.10,
    efficiency_mode="safe",   # эффективность «заморожена» прокси из базы
)

In [7]:
elast_paid.sort_values(by='elasticity_up',ascending = False)

,country_name,actual,base_pred,avg_cost,pred_budg_down,delta_down,elasticity_down,pred_budg_up,delta_up,elasticity_up
10,Nigeria,209.166667,190.308563,3745.763916,184.659042,-5.649521,0.296861,213.650009,23.341446,1.226505
7,Indonesia,344.733333,334.517395,7929.779297,328.095978,-6.421417,0.191961,370.848572,36.331177,1.086077
5,Egypt,415.600000,396.937897,6525.430176,362.105164,-34.832733,0.877536,439.644135,42.706238,1.075892
1,Brazil,506.733333,489.419861,15569.826172,445.115662,-44.304199,0.905239,540.269287,50.849426,1.038973
13,South Africa,66.600000,53.338223,4883.801270,45.998886,-7.339336,1.375999,58.665936,5.327713,0.998855
14,Казахстан,645.033333,636.083069,5123.773438,582.793579,-53.289490,0.837776,697.806519,61.723450,0.970368
0,Bolivia,98.866667,84.050606,4341.099609,76.293541,-7.757065,0.922904,92.191414,8.140808,0.968560
4,Ecuador,185.366667,170.132797,3764.539062,153.461639,-16.671158,0.979891,185.529190,15.396393,0.904963
3,Colombia,832.500000,794.847412,11342.303711,733.771912,-61.075500,0.768393,865.956360,71.108948,0.894624
11,Pakistan,1163.000000,1127.113525,7547.296387,1016.656372,-110.457153,0.980000,1213.276489,86.162964,0.764457
12,Peru,1337.766667,1271.029175,6124.316895,1150.668091,-120.361084,0.946958,1360.503174,89.473999,0.703949
2,Chile,81.800000,66.523422,2936.004395,60.693813,-5.829609,0.876324,71.141090,4.617668,0.694142
8,Mexico,328.700000,312.195251,25007.062500,303.416412,-8.778839,0.281197,329.029297,16.834045,0.539215
6,India,130.900000,120.036499,6646.168457,105.346695,-14.689804,1.223778,125.802582,5.766083,0.480361
9,Nepal,152.033333,171.170319,784.158447,170.623184,-0.547134,0.031964,177.495773,6.325455,0.369542

In [8]:
df['newbies_total'] = df['vertical_newbies_delivery_paid']+df['vertical_newbies_delivery_organic']

In [9]:
result_total = train_country_newbies_model(
    df,
    seed=42,
    holdout_days=30,
    half_life_days=60,
    top_n_countries=15,
    target_column = 'newbies_total',
    catboost_params={"iterations": 3000, "learning_rate": 0.05}
)

In [10]:
result_total['metrics_overall']

,rmse,mae,wmape_pct,rows,unique_days,unique_countries,holdout_start,last_date,train_last_date
0,64.288646,35.735495,4.70884,450,30,15,2025-09-02,2025-10-01,2025-09-01

In [11]:
elast_total = simulate_budget_elasticity(
    model=result_total["model"],
    df_model=result_total["df_model"],
    feature_columns=result_total["feature_columns"],
    categorical_features=result_total["categorical_features"],
    target_col="newbies_total",
    start_date=result_total["holdout_start"],
    end_date=result_total["last_date"],
    budg_down=0.90,
    budg_up=1.10,
    efficiency_mode="safe",   # эффективность «заморожена» прокси из базы
)

In [12]:
elast_total.sort_values(by='elasticity_up',ascending = False)

,country_name,actual,base_pred,avg_cost,pred_budg_down,delta_down,elasticity_down,pred_budg_up,delta_up,elasticity_up
7,Indonesia,824.266667,792.723572,7929.779297,774.432434,-18.291138,0.230738,891.596741,98.873169,1.247259
0,Bolivia,147.633333,131.616898,4341.099609,118.472282,-13.144615,0.998703,147.558029,15.941132,1.211177
13,South Africa,99.866667,83.911583,4883.801270,71.664940,-12.246643,1.459470,93.927025,10.015442,1.193571
1,Brazil,890.566667,868.189514,15569.826172,795.428833,-72.760681,0.838074,961.435852,93.246338,1.074032
10,Nigeria,454.233333,404.796173,3745.763916,385.216583,-19.579590,0.483690,447.645905,42.849731,1.058551
14,Казахстан,1145.666667,1122.426392,5123.773438,1028.338379,-94.088013,0.838256,1237.537476,115.111084,1.025556
3,Colombia,1359.433333,1324.361816,11342.303711,1208.121460,-116.240356,0.877708,1455.826904,131.465088,0.992667
4,Ecuador,315.033333,298.301056,3764.539062,268.954285,-29.346771,0.983797,326.509613,28.208557,0.945641
5,Egypt,703.966667,680.454163,6525.430176,620.643005,-59.811157,0.878989,741.902588,61.448425,0.903050
2,Chile,151.466667,132.857330,2936.004395,120.760910,-12.096420,0.910482,143.490631,10.633301,0.800355
12,Peru,2035.333333,1940.556763,6124.316895,1757.085815,-183.470947,0.945455,2091.395752,150.838989,0.777297
11,Pakistan,2023.233333,1967.406982,7547.296387,1778.960205,-188.446777,0.957843,2090.862305,123.455322,0.627503
8,Mexico,583.733333,564.586060,25007.062500,546.009827,-18.576233,0.329024,593.141724,28.555664,0.505781
6,India,300.866667,288.398560,6646.168457,251.577042,-36.821518,1.276758,302.439575,14.041016,0.486861
9,Nepal,348.233333,348.567657,784.158447,346.875336,-1.692322,0.048551,362.405701,13.838043,0.396997

In [13]:
elast_total.to_csv('elast_for_total_newbies.csv')

In [16]:
# Пример: подсчитать дни/строки в train
# Требуемые переменные: df_model, holdout_start, X_train (см. train_country_newbies_model в personal/finance.ipynb)

holdout_start = result['holdout_start']
last_date = result['last_date']
train_last_date = ['2025-08-31']
df_model = result['df_model'].copy()
n_train_days = df_model.loc[df_model['day'] < holdout_start, 'day'].nunique()
n_train_rows = X_train.shape[0] if 'X_train' in globals() else len(df_model.loc[df_model['day'] < holdout_start])
print(f"Train unique days: {n_train_days}")
print(f"Train rows: {n_train_rows}")
print(f"holdout_start: {holdout_start}, last_date: {last_date}, train_last_date: {train_last_date}")

Train unique days: 229
Train rows: 3435
holdout_start: 2025-09-01 00:00:00, last_date: 2025-09-30 00:00:00, train_last_date: ['2025-08-31']